services:
  diffsense:
    build: .
    image: ghcr.io/araragi-koyomin/diffsense:latest
    container_name: diffsense
    ports:
      - '9090:3000'
    environment:
      - DIFFSENSE_SECRET=${DIFFSENSE_SECRET:-}
    command: web
